
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Meeting_App.Models
{

using System;
    using System.Collections.Generic;
    
public partial class Subscription
{

    public int SubscriptionID { get; set; }

    public string SubscriptionName { get; set; }

    public Nullable<int> NumberOfUsers { get; set; }

    public Nullable<System.DateTime> CreatedDate { get; set; }

    public Nullable<int> IsActive { get; set; }

    public string CompanyName { get; set; }

    public Nullable<int> Price { get; set; }

    public Nullable<int> CreatedBy { get; set; }

    public Nullable<int> ModifiedBy { get; set; }

    public Nullable<System.DateTime> ModifiedDate { get; set; }

}

}
